version: "3.9"
services:
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
volumes:
  db-store:
